added PR template
ergomake/layerform pull request #66
Opened 2023-09-08 17:56 UTC by SaumyaBhushan

2023-09-08 17:58 UTC, SaumyaBhushan commented
Hi @lucasfcosta . I have added a PR template . Please review .

2023-09-08 17:58 UTC, SaumyaBhushan commented
I can add issue template as well . Let me know if you want that

2023-09-09 20:39 UTC, lucasfcosta requested changes
Hey @SaumyaBhushan, thanks so much for the PR!

Really appreciate that. Just one comment on my end and then this will be good to go.

2023-09-09 20:42 UTC, vieiralucas requested changes
Hi @SaumyaBhushan 

First of all, thank you so much for taking the time and making this PR.
Overall this is looking pretty good, amazing.

I just think we should remove the `Check List`.
Can you updated it?

Thank you again, cheers.

2023-09-09 20:42 UTC, vieiralucas commented on .github/pull_request_template.md
> +
Can you remove this section? Let's keep this as simple as possible for now, we can always add more stuff later if think it's needed.
```suggestion
```

2023-09-09 20:44 UTC, lucasfcosta approved these changes

2023-09-09 20:46 UTC, vieiralucas approved these changes

2023-09-09 20:48 UTC, vieiralucas commented
Thank you @SaumyaBhushan. Welcome the the contributors list 😄 
Closes #65

2023-09-09 20:48 UTC, merged

2023-09-09 20:50 UTC, SaumyaBhushan commented
Hi @vieiralucas @lucasfcosta . Please let me know if you have more such issues or issue related to ci-cd Or devops. I would be happy to contribute.