Validate name of layer instances to only accept alphanumeric characters
ergomake/layerform pull request #72
Opened 2023-09-10 17:53 UTC by rafiramadhana

Add alphanumeric regexp to validate instance name.

## Why this matters

This PR validates name of layer instances to only accept alphanumeric characters.

## Solution

Add regexp `^[A-Za-z0-9][A-Za-z0-9_-]*[A-Za-z0-9]$` to validate name of layer instances.

## How to test it

I run it locally and add some e2e tests as mentioned in https://github.com/ergomake/layerform/issues/67#issuecomment-1712731234.

```
➜  layerform git:(67-validate-layer-name) ✗ go run . spawn foo 'this has spaces'
Invalid name: this has spaces
Name must must start and end with an alphanumeric character and can include dashes and underscores in between.
exit status 1
```

## Note to reviewers

2023-09-10 23:23 UTC, vieiralucas requested changes
Hi @rafiramadhana, thank you so much for this. I found a typo in the error message, do you mind fixing that? Thank you.

2023-09-10 23:23 UTC, vieiralucas commented on cmd/cli/spawn.go
> +			fmt.Fprintln(os.Stderr, "Name must must start and end with an alphanumeric character and can include dashes and underscores in between.")
```suggestion
			fmt.Fprintln(os.Stderr, "Name must start and end with an alphanumeric character and can include dashes and underscores in between.")
```

2023-09-10 23:24 UTC, vieiralucas requested changes
Another thing is a [formatting issue](https://github.com/ergomake/layerform/actions/runs/6138637862/job/16658539814?pr=72#step:6:25), can you also run `make fmt` and check in in the changes?

2023-09-11 16:42 UTC, rafiramadhana commented
> Another thing is a [formatting issue](https://github.com/ergomake/layerform/actions/runs/6138637862/job/16658539814?pr=72#step:6:25), can you also run `make fmt` and check in in the changes?

updated https://github.com/ergomake/layerform/pull/72/commits/83fa7bceec673e6a60ab5cfd4afa48cab8d5d1c4

2023-09-11 16:42 UTC, rafiramadhana commented on cmd/cli/spawn.go
> +			fmt.Fprintln(os.Stderr, "Name must must start and end with an alphanumeric character and can include dashes and underscores in between.")
updated https://github.com/ergomake/layerform/pull/72/commits/cea1d2e612f1480cea197664fb788305f05c80a8

2023-09-11 18:01 UTC, vieiralucas approved these changes

2023-09-11 18:01 UTC, vieiralucas commented
Awesome work @rafiramadhana, thank you for the contribution!

2023-09-11 18:02 UTC, merged