Validate name of layer definitions to only accept alphanumeric characters
ergomake/layerform pull request #74
Opened 2023-09-11 17:40 UTC by rafiramadhana

## Why this matters

This PR validates name of layer definitions to only accept alphanumeric characters.

## Solution

Add regexp `^[A-Za-z0-9][A-Za-z0-9_-]*[A-Za-z0-9]$` to validate name of layer definitions.

## How to test it

Run `make test`.

Or to make it specific, you can do `go test -v -run=TestToLayers_ValidateNameOfLayerDefinitions github.com/ergomake/layerform/internal/layerfile`.

## Note to reviewers

2023-09-11 17:44 UTC, rafiramadhana commented on internal/layerfile/layerfile_test.go
> +			}
The reason why im doing if-else in this test: 

I Kept getting this error when using `assert.Equal(t, tt.err, err)`

```suggestion
			_, err := tt.lf.ToLayers()
			assert.Equal(t, tt.err, err)
```

```
go test -v -run=TestToLayers_ValidateNameOfLayerDefinitions github.com/ergomake/layerform/internal/layerfile
=== RUN   TestToLayers_ValidateNameOfLayerDefinitions
=== RUN   TestToLayers_ValidateNameOfLayerDefinitions/Name_has_spaces
    layerfile_test.go:136: 
                Error Trace:    /home/rafi/Documents/oss/github/layerform/internal/layerfile/layerfile_test.go:136
                Error:          Not equal: 
                                expected: invalid name: invalid name for a layer definition
                                actual  : invalid name: invalid name for a layer definition
                            
                                Diff:
                                --- Expected
                                +++ Actual
                                @@ -2,4 +2,5 @@
                                  msg: (string) (len=49) "invalid name: invalid name for a layer definition",
                                - stack: (*errors.stack)((len=3) {
                                -  (uintptr) 0x5b7024,
                                + stack: (*errors.stack)((len=4) {
                                +  (uintptr) 0x5b639d,
                                +  (uintptr) 0x5b724e,
                                   (uintptr) 0x4e89ab,
                Test:           TestToLayers_ValidateNameOfLayerDefinitions/Name_has_spaces
=== RUN   TestToLayers_ValidateNameOfLayerDefinitions/Name_has_special_character
    layerfile_test.go:136: 
                Error Trace:    /home/rafi/Documents/oss/github/layerform/internal/layerfile/layerfile_test.go:136
                Error:          Not equal: 
                                expected: invalid name: invalid!
                                actual  : invalid name: invalid!
                            
                                Diff:
                                --- Expected
                                +++ Actual
                                @@ -2,4 +2,5 @@
                                  msg: (string) (len=22) "invalid name: invalid!",
                                - stack: (*errors.stack)((len=3) {
                                -  (uintptr) 0x5b7099,
                                + stack: (*errors.stack)((len=4) {
                                +  (uintptr) 0x5b639d,
                                +  (uintptr) 0x5b724e,
                                   (uintptr) 0x4e89ab,
                Test:           TestToLayers_ValidateNameOfLayerDefinitions/Name_has_special_character
=== RUN   TestToLayers_ValidateNameOfLayerDefinitions/Valid_name
--- FAIL: TestToLayers_ValidateNameOfLayerDefinitions (0.00s)
    --- FAIL: TestToLayers_ValidateNameOfLayerDefinitions/Name_has_spaces (0.00s)
    --- FAIL: TestToLayers_ValidateNameOfLayerDefinitions/Name_has_special_character (0.00s)
    --- PASS: TestToLayers_ValidateNameOfLayerDefinitions/Valid_name (0.00s)
FAIL
FAIL    github.com/ergomake/layerform/internal/layerfile        0.005s
FAIL
```

2023-09-11 18:24 UTC, vieiralucas requested changes
This looks pretty good, I think we can make it even better.
Lets introduce a `ErrInvalidName` variable and return that.
Then, the caller should check the `error` to display a good error message.

Add the error variable before `alphanumericRegex`, like this:
```go
var ErrInvalidDefinitionName = errors.New("invalid layer definition name")
```

Then, we change line 46 to wrap this error:
```go
			return nil, errors.Wrap(ErrInvalidDefinitionName, l.Name)
```

Finally, we should go here https://github.com/ergomake/layerform/blob/a4f6211eb76c602ca5ad8f6429d0afa531499d48/cmd/cli/configure.go#L94-L98

And change it to add an error message similar to the one we added in #72

```go
		err = configure.Run(ctx, fpath)
		if err != nil {
			if errors.Is(err, layerfile.ErrInvalidDefinitionName) {
				fmt.Fprintln(
					os.Stderr,
					"Name must start and end with an alphanumeric character and can include dashes and underscores in between.",
				)
			}

			fmt.Fprintf(os.Stderr, "%s\n", err)
			os.Exit(1)
		}
```

2023-09-13 00:08 UTC, rafiramadhana commented
> This looks pretty good, I think we can make it even better. Lets introduce a `ErrInvalidName` variable and return that. Then, the caller should check the `error` to display a good error message.

updated https://github.com/ergomake/layerform/pull/74/commits/cb01bb58ddd200ab77ebc591fb67eef0f75d6a13

2023-09-13 00:50 UTC, vieiralucas approved these changes

2023-09-13 00:50 UTC, vieiralucas commented
Nice @rafiramadhana, this LGTM. There is only one extra small thing I would suggest us to change in the way the tests were written. But I'll not block merging. I'll just submit another PR right away to show you.

2023-09-13 00:51 UTC, merged