feat: --force flag to layerform kill
ergomake/layerform pull request #95
Opened 2023-09-17 01:19 UTC by lanjoni

## Why this matters

This PR aims to add the `--force` flag to the `layerform kill` command, adding the ability to kill multiple layers at once as opened in the issue https://github.com/ergomake/layerform/issues/60

## Solution

In addition to adding the check for the `--force` flag, a function called `GetDependants` was created, very similar to the existing function `HasDependants`, but this time returning a list of the layers to be killed in order. The verification occurs recursively, always bringing the first layers as children.

## How to test it

The best way to test would be with `examples/local` since `--force` for cloud has not yet been implemented (because I still need to test and verify that it will work correctly). To test, simply use:

```sh
$ layerform configure
$ layerform spawn foo default
$ layerform spawn bar
$ layerform spawn baz
```

So when you try to run:

```sh
$ layerform kill foo default
```

The following message will appear:

```
✗ Preparing to kill instance "default" of layer "foo"
can't kill this layer because other layers depend on it
use the --force flag to kill it anyway
exit status 1
```

To force just run:

```sh
$ layerform kill foo default --force
```

Done! The child layers will be killed first until reaching `foo=default`!

## Note to reviewers

I haven't implemented the Cloud version yet, so the `HasDependants` function still exists. I would like to check if the operation is the same (bearing in mind that the main difference is the way http requests are made).

2023-09-17 01:21 UTC, J0sueTM commented
LGTM

2023-09-17 01:21 UTC, J0sueTM approved these changes
LGTM

2023-09-17 23:32 UTC, vieiralucas requested changes
Hi @lanjoni 

Thank you so much for the contribution, this looks great!
You just forgot to handle one error case.

About the `cloud` implementation, the `cloud` is not live yet so you'll not be able to test it out, so I don't think it makes sense for you to worry about it, I'll do it later.

2023-09-17 23:32 UTC, vieiralucas commented on pkg/command/kill/local.go
> +			c.Run(ctx, d.DefinitionName, d.InstanceName, autoApprove, vars, force)
This function returns an `error`, we should check it and return it wrapped.
Like:
```suggestion
			err = c.Run(ctx, d.DefinitionName, d.InstanceName, autoApprove, vars, force)
			if err != nil {
				return errors.Wrapf(err, "fail to kill dependant %s=%s", d.DefinitionName, d.InstanceName)
			}
```

2023-09-17 23:35 UTC, vieiralucas commented
Also, another thing that would be great is if we added test cases for this to the `.github/workflows/e2e.yml` workflow.
But just if you feel like doing it, I can do it later, not a blocker to merge the PR.

2023-09-18 01:37 UTC, merged

2023-09-18 01:38 UTC, vieiralucas commented
Awesome, thank you @lanjoni!